services:
  - type: worker   # background worker, sleeps nahi hoga
    name: novax-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false   # iski value Render dashboard mein dalenge